// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using S3.Services.Record.Utility;

namespace S3.Services.Record.Migrations
{
    [DbContext(typeof(RecordDbContext))]
    [Migration("20191115230133_Migration2")]
    partial class Migration2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("S3.Services.Record.Domain.Rule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("A_DistinctionCutoff");

                    b.Property<float>("B_VeryGoodCutoff");

                    b.Property<float>("CAPercentage");

                    b.Property<float>("C_CreditCutoff");

                    b.Property<float?>("ClassActivitiesPercentage");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<float>("F_FailCutoff");

                    b.Property<float>("FirstExamPercentage");

                    b.Property<float?>("HomeworkPercentage");

                    b.Property<bool>("IsDefault");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<float>("P_PassCutoff");

                    b.Property<Guid>("SchoolId");

                    b.Property<float?>("SecondExamPercentage");

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("Id");

                    b.ToTable("Rules");
                });

            modelBuilder.Entity("S3.Services.Record.Domain.StudentScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ClassId");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("ExamType")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<float>("Mark");

                    b.Property<Guid>("RuleId");

                    b.Property<Guid>("SchoolId");

                    b.Property<int>("Session");

                    b.Property<Guid>("StudentId");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("Id");

                    b.ToTable("StudentScores");
                });
#pragma warning restore 612, 618
        }
    }
}
